# Generated by Django 4.0.8 on 2022-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=6)),
                ('color2', models.CharField(max_length=6)),
                ('color3', models.CharField(max_length=6)),
                ('color4', models.CharField(max_length=6)),
                ('color5', models.CharField(max_length=6)),
            ],
        ),
    ]
