# Generated by Django 4.0.8 on 2022-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('favPaletteIDs', models.JSONField()),
                ('histPaletteIDs', models.JSONField()),
            ],
        ),
    ]
